### ISSUE TITLE
Mbot & Physical Web

### ISSUE THREAD

**Issue by jefBinomed** [binomed/PrezWeb#11]
Préparer un beacon avec l'url

**Comment by jefBinomed** [comment]
beacon configuré

**Comment by beaufortfrancois** [comment]
Est-ce que l'on peut creer une issue avec une liste de tous les objets a apporter/configurer/etc?

**Comment by jefBinomed** [comment]
yep c'est une bonne idée !

Le lun. 7 nov. 2016 à 09:50, François Beaufort notifications@github.com a
écrit :
