### ISSUE TITLE
WebNFC sur un tag

### ISSUE THREAD

**Issue by jefBinomed** [binomed/PrezWeb#15]

**Comment by jefBinomed** [comment]
reste à définir ce qu'on met dans le tag

**Comment by jefBinomed** [comment]
j'ai mis un lien vers le devfest

**Comment by beaufortfrancois** [comment]
Tu peux creer une issue specifique pour que l'on n'oublie pas de mettre quelque chose sur le tag?

**Comment by jefBinomed** [comment]
c'est déjà fait, j'ai écrit hier sur 3 tags pour faire ça justement, d'où
le fait que j'ai clos l'issue

Le lun. 7 nov. 2016 à 09:45, François Beaufort notifications@github.com a
écrit :

**Comment by beaufortfrancois** [comment]
Si tu mets un lien vers le devfest et que la demo est d'ecrire un lien vers le devfest, ca ne va pas etre tres pratique pour la demo non?

**Comment by jefBinomed** [comment]
non non t'en fais pas :) j'ai écrit sur mes tags :
https://jef.binomed.fr/PrezWeb/index_phone.html et du coup, je vais
scanner, ce qui va m'ouvrir la bonne page, et je vais écrire après sur le
tag https://devfest.gdgnantes.com https://devfest.gdgnantes.coml et je
montrerais ensuite qu'on a bien écrit en rescannant le tag qui devrait
s'ouvrir cette fois sur le site du devfest :)

Le lun. 7 nov. 2016 à 09:56, François Beaufort notifications@github.com a
écrit :

**Comment by beaufortfrancois** [comment]
Oki.
