### ISSUE TITLE
trouver l'image welcome to the futur

### ISSUE THREAD

**Issue by jefBinomed** [binomed/PrezWeb#33]

**Comment by jefBinomed** [comment]
avoir une image super cool & rajouter un slide , bon en réalité c'est pas si ouf que ça

**Comment by jefBinomed** [comment]
@beaufortfrancois j'ai fait 2 versions à toi de voir laquelle tu trouves la plus sympa

**Comment by beaufortfrancois** [comment]
Je ne suis pas fan de "BON PAS TANT QUE ÇA FINALEMENT", comment pourrait-on le tourner?

**Comment by jefBinomed** [comment]
on pourrait faire simplement "NOT REALLY" ?

Le lun. 7 nov. 2016 à 09:47, François Beaufort notifications@github.com a
écrit :

**Comment by beaufortfrancois** [comment]
Mais pourquoi "not really?" a ce moment la?
On presente derriere WebNFC et WebUSB. Quel est notre rationale?

**Comment by jefBinomed** [comment]
bah en fait, c'est histoire de dire que en gros on vend du rêve en premier
lieu mais qu'en réalité, tout n'est pas encore hyper fonctionnel. Genre
pour le coup de l'hologramme par exemple, tu vois un truc de ouf et en
réel, c'est un hologramme mais pas avec autant de choses qu'on voudrait
d'où le "not really"

Le lun. 7 nov. 2016 à 09:57, François Beaufort notifications@github.com a
écrit :

**Comment by beaufortfrancois** [comment]
https://github.com/binomed/PrezWeb/pull/42
