### ISSUE TITLE
slide final

### ISSUE THREAD

**Issue by jefBinomed** [binomed/PrezWeb#36]

**Comment by beaufortfrancois** [comment]
Y a une image oki mais le contenu c'est quoi?

**Comment by jefBinomed** [comment]
faut qu'on trouve mais j'aurais bien mis un truc en mode, vous voyez le web
bouge beaucoup en ce moment, il est important de suivre ses évolutions.
Même si tout n'est pas encore sec aujourd'hui, vous voyez qu'il prend des
nouvelles directions qui nous permettent de faire plus de choses ! bref, le
web c'est cool !

Le lun. 7 nov. 2016 à 09:46, François Beaufort notifications@github.com a
écrit :

**Comment by beaufortfrancois** [comment]
+1!

**Comment by beaufortfrancois** [comment]
@jefBinomed will find out what to say.
