### ISSUE TITLE
Welcome to the Futur [duplicates]

### ISSUE THREAD

**Issue by beaufortfrancois** [binomed/PrezWeb#39]
On peut choisir un?

![screenshot 2016-11-07 at 9 41 10 am](https://cloud.githubusercontent.com/assets/634478/20051246/59c80744-a4ce-11e6-8eaf-fa9fbe6ab18d.png)

**Comment by jefBinomed** [comment]
On a dit qu'on prenait juste l'image de l'homme qui regarde à travers la porte
