### ISSUE TITLE
My Google Assistant Demo improvements

### ISSUE THREAD

**Issue by beaufortfrancois** [binomed/PrezWeb#41]
Ce serait pas mal de forcer un click sur la demo de Google Assistant pour eviter de faire apparaitre le prompt tout le temps. Et aussi, il faudra penser a reinitialiser la permission.

**Comment by jefBinomed** [comment]
comment ça ?

Le lun. 7 nov. 2016 à 10:00, François Beaufort notifications@github.com a
écrit :

**Comment by beaufortfrancois** [comment]
https://github.com/binomed/PrezWeb/pull/42
