### ISSUE TITLE
Remove grammar slide ou pas ?

### ISSUE THREAD

**Issue by beaufortfrancois** [binomed/PrezWeb#46]
From https://hacks.mozilla.org/2016/01/firefox-and-the-web-speech-api/, 

> Note: Chrome does not appear to deal with specific grammars; instead it just returns all results, and you can deal with them as you want. This is because Chrome’s server-side speech recognition has more processing power available than the client-side solution Firefox uses. There are advantages to each approach.

Dans ces cas la, retirons `grammar`, qu'en penses-tu?

**Comment by jefBinomed** [comment]
je penses qu'on peut le garder en précisant que c'est firefox only, c'est pas déconnant car ça fait parti quand même de la spec
